### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Sajan Adhikari",
    "email": "sajan21sasssa2@example.com",
    "password": "Psword@3"
}

### Login with registered user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "sajan@example.com",
    "password": "password123"
}

### Create a Post (Requires Authentication)
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY1MWM3ODc3MzE5OTIwMjkzMWMyMWIyIn0sImlhdCI6MTcxNjYzNTYzNywiZXhwIjoxNzE2NjM5MjM3fQ.VFjgYNPwWVUN9S3xZR7xVB6lTDO16sVAo0eAlelrcro

{
  "title": "My third Post on this new Post Model API",
  "content": "This is the content of my third post."
}

### Get All Posts
GET http://localhost:5000/api/posts

### Get Single Post by ID
GET http://localhost:5000/api/posts/6651c86673199202931c21d0
### Update Post by ID (Requires Authentication)
PUT http://localhost:5000/api/posts/6651c86673199202931c21d0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY0ZjU5OWQwN2VmMWM3NTI2MjU3YjYwIn0sImlhdCI6MTcxNjYzNTgwNSwiZXhwIjoxNzE2NjM5NDA1fQ.-seKrsnrsUL5fOwlXO6BBaFOqV5hOeOa6LVP4DTRy40

{
  "title": "thik xa ni ta",
  "content": "Updated content of the post."
}

### Delete Post by ID (Requires Authentication)
DELETE http://localhost:5000/api/posts/66519121a09174380d92bf41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY0ZjU5OWQwN2VmMWM3NTI2MjU3YjYwIn0sImlhdCI6MTcxNjYyMjE0MCwiZXhwIjoxNzE2NjI1NzQwfQ.CD4XBaZPXcfvlUqF-Zj2czc5CTJql_YDE0uLeufVy2M

### Like a Post
PUT http://localhost:5000/api/posts/like/6651c86673199202931c21d0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY1MWM3ODc3MzE5OTIwMjkzMWMyMWIyIn0sImlhdCI6MTcxNjYzNTYzNywiZXhwIjoxNzE2NjM5MjM3fQ.VFjgYNPwWVUN9S3xZR7xVB6lTDO16sVAo0eAlelrcro

### Unlike a Post
PUT http://localhost:5000/api/posts/unlike/66519121a09174380d92bf41
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY1MWM3ODc3MzE5OTIwMjkzMWMyMWIyIn0sImlhdCI6MTcxNjYzNTYzNywiZXhwIjoxNzE2NjM5MjM3fQ.VFjgYNPwWVUN9S3xZR7xVB6lTDO16sVAo0eAlelrcro

### Comment on a Post
POST http://localhost:5000/api/posts/comment/6651c86673199202931c21d0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY1MWM3ODc3MzE5OTIwMjkzMWMyMWIyIn0sImlhdCI6MTcxNjYzNTYzNywiZXhwIjoxNzE2NjM5MjM3fQ.VFjgYNPwWVUN9S3xZR7xVB6lTDO16sVAo0eAlelrcro

{
  "text": "thikai blog xa bro."
}

### Delete a Comment
DELETE http://localhost:5000/api/posts/comment/:postId/:commentId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY1MWM3ODc3MzE5OTIwMjkzMWMyMWIyIn0sImlhdCI6MTcxNjYzNTYzNywiZXhwIjoxNzE2NjM5MjM3fQ.VFjgYNPwWVUN9S3xZR7xVB6lTDO16sVAo0eAlelrcro

### Get All Users
GET http://localhost:5000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY1MWM3ODc3MzE5OTIwMjkzMWMyMWIyIn0sImlhdCI6MTcxNjYzNTYzNywiZXhwIjoxNzE2NjM5MjM3fQ.VFjgYNPwWVUN9S3xZR7xVB6lTDO16sVAo0eAlelrcro

### Retrieve user profile
GET http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY0ZjU5OWQwN2VmMWM3NTI2MjU3YjYwIn0sImlhdCI6MTcxNjYzOTI5NywiZXhwIjoxNzE2NjM5MzU3fQ.RcpKsWxuYyL2M9lJmbeS7qIr3ih__D0xcIr6FcJJUYc
### Update user profile
PUT http://localhost:5000/api/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjY0ZjU5OWQwN2VmMWM3NTI2MjU3YjYwIn0sImlhdCI6MTcxNjYzOTI5NywiZXhwIjoxNzE2NjM5MzU3fQ.RcpKsWxuYyL2M9lJmbeS7qIr3ih__D0xcIr6FcJJUYc

  {
    "name": "Sajan Adhikari",
    "email": "sajan@example.com",
    "password": "password@123"
  }
  